PLEASE DO ,1 <- #6
DO ,1 SUB 1 <- #3
DO READ OUT ,1
PLEASE WRITE IN ,1
DO ,1 SUB 1 <- #4
PLEASE ABSTAIN FROM ,1
PLEASE COME FROM ,1
DO ,1 SUB 1 <- #1
DO READ OUT ,1
DO ,1 SUB 1 <- #5
PLEASE WRITE IN ,1
DO ,1 SUB 1 <- #6
PLEASE ABSTAIN FROM ,1
PLEASE COME FROM ,1
